module.exports = {
  Course: require('./Course'),
  Teacher: require('./Teacher'),
  Enrollment: require('./Enrollment'),
  Payment: require('./Payment'),
  Attendance: require('./Attendance'),
  Token: require('./Token'),
  Testimonial: require('./Testimonial'),
  Schedule: require('./Schedule'),
  Resource: require('./Resource'),
  Lead: require('./Lead'),
  Contact: require('./Contact'),
  FAQ: require('./FAQ'),
  Consultation: require('./Consultation'),
  Workshop: require('./Workshop'),
  WorkshopEnrollment: require('./WorkshopEnrollment'),
  DynamicPricing: require('./DynamicPricing'),
  Progress: require('./Progress'),
  FreeResourceTracking: require('./FreeResourceTracking'),
}
