const registerHealth = require('./health.routes.js')
const registerPayments = require('./payments.routes.js')
const registerCourses = require('./courses.routes.js')
const registerDemo = require('./demo.routes.js')
const registerTeachers = require('./teachers.routes.js')
const registerEnrollments = require('./enrollments.routes.js')
const registerPricing = require('./pricing.routes.js')
const registerDebug = require('./debug.routes.js')
const registerMedia = require('./media.routes.js')
const registerMe = require('./me.routes.js')
const registerAdminEnrollments = require('./admin/enrollments.routes.js')
const registerAdminAttendance = require('./admin/attendance.routes.js')
const registerAdminTokens = require('./admin/tokens.routes.js')
const registerAdminSchedules = require('./admin/schedules.routes.js')
const registerAdminResources = require('./admin/resources.routes.js')
const registerFreeResources = require('./freeResources.routes.js')
const registerResources = require('./resources.routes.js')
const registerDev = require('./dev.routes.js')
const registerLeads = require('./leads.routes.js')
const registerContact = require('./contact.routes.js')
const registerFaqs = require('./faqs.routes.js')
const registerConsultations = require('./consultations.routes.js')
const registerWorkshops = require('./workshops.routes.js')
const registerTestimonials = require('./testimonials.routes.js')

function registerRoutes(app) {
  registerHealth(app)
  registerPayments(app)
  registerCourses(app)
  registerDemo(app)
  registerTeachers(app)
  registerEnrollments(app)
  registerPricing(app)
  registerDebug(app)
  registerMedia(app)
  registerMe(app)
  registerAdminEnrollments(app)
  registerAdminAttendance(app)
  registerAdminTokens(app)
  registerAdminSchedules(app)
  registerAdminResources(app)
  registerFreeResources(app)
  registerResources(app)
  registerDev(app)
  registerLeads(app)
  registerContact(app)
  registerFaqs(app)
  registerConsultations(app)
  registerWorkshops(app)
  registerTestimonials(app)
}

module.exports = registerRoutes
